services:
  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    container_name: crispr_redis
    volumes:
      - /mnt/media/crispr_app/redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    stop_signal: SIGTERM
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crispr_backend
    env_file:
      - ./.env.prod
    environment:
      - PYTHONPATH=/app:/app/backend
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - /mnt/media/crispr_app/data:/data
    networks:
      - default

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    container_name: crispr_frontend
    depends_on:
      - backend
    networks:
      - default

# Celery Worker
  celery-worker:
    build:
      context: ./backend/celery_app
      dockerfile: Dockerfile
    container_name: celery_worker
    cpu_shares: 512 
    env_file:
      - ./.env.prod
    environment:
      - PYTHONPATH=/app:/app/backend
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - /mnt/media/crispr_app/data:/data
    command: ["micromamba","run","-n","celery","celery","-A","backend.celery_app.celery_app.celery_app","worker","--loglevel=info", "--concurrency=1"]
    networks:
      - default

  crispr-proxy:
    image: nginx:alpine
    container_name: crispr_proxy
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - default
      - edge

volumes:
  postgres_data:
  redis_data:

networks:
  edge:
    external: true
